In [1]:
import higlass as hg
import numpy as np
import pandas as pd
import bioframe
import cooltools
import cooler

import utils as utils

### creating ctcf table

In [2]:
###importing ctcf peaks ####
ctcf_path='/project/fudenber_735/collaborations/karissa_2022/2022_09_features_for_RNAseq/ChIP-seq_in_WT-parental-E14'
ctcf = bioframe.read_table(ctcf_path+'/CTCF_peaks_called_on_4reps_foundInatLeast2reps_noBlacklist.bed', schema='bed')#.query(f'chrom in {clr.chromnames}')

### importing ctcf motifs ###
direct='/project/fudenber_735/motifs/mm10/jaspar/MA0139.1.tsv.gz'
motif=bioframe.read_table(direct)
motif=motif.rename(columns={0: 'chrom', 1: 'start',2:'end',3:'name',4:'score',5:'pval',6:'strand'})

### overlap between peaks and motifs### 
peaks_motifs = bioframe.overlap(ctcf,motif,how='inner')
peaks_motifs=peaks_motifs.rename(columns={'strand':'strand_','strand_':'strand'})
peaks_motifs=peaks_motifs[['chrom','start','end','strand']]

In [3]:
region_ctcf_motif = utils.region_data_frame(peaks_motifs, region = 'chr1:34000000-44000000')
region_ctcf_motif

/home1/rahmanin/start/polychrom/projects/Site_wise_occupancy/utils.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  region_dataframe['mid']=(region_dataframe.end+region_dataframe.start)/2
/home1/rahmanin/start/polychrom/projects/Site_wise_occupancy/utils.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  region_dataframe['lattice_loc'] = ((region_dataframe['mid'] - region_start) // lattice_size).astype('int')

    chrom     start       end strand         mid  lattice_loc
0    chr1  34005641  34006016      +  34005828.5           23
1    chr1  34011003  34011576      +  34011289.5           45
2    chr1  34049624  34049965      -  34049794.5          199
3    chr1  34068201  34068742      -  34068471.5          273
4    chr1  34093645  34094093      +  34093869.0          375
..    ...       ...       ...    ...         ...          ...
268  chr1  43738188  43738540      -  43738364.0        38953
269  chr1  43760145  43760509      +  43760327.0        39041
270  chr1  43762617  43762972      -  43762794.5        39051
271  chr1  43898949  43899413      +  43899181.0        39596
272  chr1  43902827  43903164      +  43902995.5        39611

[273 rows x 6 columns]

In [4]:
df = region_ctcf_motif
repetitive_values = df['lattice_loc'][df['lattice_loc'].duplicated()]

unique_values = df['lattice_loc'].unique()

In [8]:
region_ctcf_motif.to_csv('chr1_34mb_44mb.csv',index=False)